listening-port=3478
tls-listening-port=5349
realm=${COTURN_DOMAIN}
server-name=${COTURN_DOMAIN}
external-ip=${SERVER_EXTERNAL_IP}
static-auth-secret=${COTURN_SECRET}
fingerprint
lt-cred-mech
user-quota=12
total-quota=100
